### ISSUE TITLE
can't scroll horizontally on mobile

### ISSUE THREAD

**Issue by kajtielplu** [GRA0007/crab.fit#233] opened 2022-11-03 08:54 UTC
**Describe the bug**
you can't scroll sideways and see the whole schedule on mobile devices.

**To Reproduce**
on android or iOS, load a schedule that is wide enough to require scrolling sideways. when trying to scroll horizontally like one does vertically, the page will not scroll, and touches will instead be registered as marking availability on the schedule.

**Expected behavior**
i expected scrolling sideways to function like scrolling up and down.

**Screenshots**
[imgur video](https://imgur.com/a/XoAZRIF)

**Smartphone (please complete the following information):**
 - Device: iPhone 8 (but was told about the issue by my friends who have different android phones)
 - OS: iOS 15.6.1
 - Browser: Firefox
 - Version: 32.1

**Comment by GRA0007** [comment] 2023-06-11 15:38
Duplicate of #118

**Closed by GRA0007** 2023-06-11 15:38 UTC
Labels: bug
