### ISSUE TITLE
"Days of the week" mode doesn't work in chrome

### ISSUE THREAD

**Issue by lyudico** [GRA0007/crab.fit#301] opened 2023-08-01 12:48 UTC
### Description of the bug

When I try to create a new poll based on days of the week, the schedule view does not load: there is just an empty box without columns or rows and no labels:
![image](https://github.com/GRA0007/crab.fit/assets/22282224/a663a56a-a75f-4576-b763-9ffb0539b97c)
The date-based poll still works.
I'm using google chrome.

### To reproduce

Try to create a new poll using days of the week in google Chrome, Version 115.0.5790.114

**Comment by GRA0007** [comment] 2023-08-01 12:52
Thanks, this is a duplicate of #299 and we're working on it :)

**Closed by GRA0007** 2023-08-01 12:52 UTC
Labels: bug
