### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by darkranger778** [GRA0007/crab.fit#204] opened 2022-07-18 08:20 UTC
**create themes for different crabfit users**

**Describe the solution you'd like**
The user to change the colour to whatever they desire or add their company graphics to the hotboard

**Describe alternatives you've considered**
I haven't apart from having more coloures than orange 

**Additional context**
.

**Comment by GRA0007** [comment] 2022-08-19 08:34
Thanks for your feature request! This is a duplicate of #116.

**Closed** 2022-08-19 08:34 UTC
Labels: enhancement
